---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: postgres
    spec:
      containers:
      - image: postgres:9.5
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pgdata-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata-storage
        persistentVolumeClaim:
          claimName: pgdata-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pv-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: generic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    k8s-app: postgres
